language: python
python:
  - "3.6"

env:
  - SKIP_DEPS_CHECK=1

addons:
  apt:
    packages:
    - libleveldb-dev
    - libsqlite3-dev


# command to install dependencies
install:
  - pip install -r requirements_test.txt
  - pip install coveralls

# command to run tests
script:
  - coverage run -m unittest discover boa_test
  - pycodestyle boa
  - pycodestyle boa_test


after_success:
    coveralls
